#!/bin/node

const { readFileSync } = require('fs');
const { parse } = require('yaml');
const { protocol, host, port } = parse(readFileSync('./configuration/client.yaml', 'utf-8'));

const url = `${protocol}://${host}:${port}`;
const cmd = process.argv[2];
const args = process.argv.splice(3);

const commands = [
	{ name: 'get', func: require('./commands/get_fleet') },
	{ name: 'create', func: require('./commands/create_fleet') },
	{ name: 'register-vehicle', func: require('./commands/register_vehicle') },
	{ name: 'localize-vehicle', func: require('./commands/localize_vehicle') }
]

//execute_command(commands, url, cmd, args);
for (var i = 0; i < commands.length; i++) {
	if (commands[i].name == cmd) {
		commands[i].func(url, args);
		break;
	}
}
